config/routes.rb
Rails.application.routes.draw do

  resources :listings

  devise_for :users
  root to: "home#index"

end

app/models/detail.rb
class Detail < ActiveRecord::Base
	belongs_to :listing
end

app/models/listing.rb
class Listing < ActiveRecord::Base
	belongs_to :user

	has_many :details
	has_many :specs

	accepts_nested_attributes_for :details,
  															reject_if: proc { |attributes| attributes['name'].blank? },
  															allow_destroy: true
 	accepts_nested_attributes_for :specs,
  															reject_if: proc { |attributes| attributes['status'].blank? },
  															allow_destroy: true

  validates :title, :description, :image, presence: true

	has_attached_file :image, styles: { :medium => "400x400#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/spec.rb
class Spec < ActiveRecord::Base
	belongs_to :listing
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  has_many :listings

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	before_action :find_listing, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@listing = Listing.all.order("created_at DESC")
	end

	def show
	end

	def new
		@listing = Listing.new
	end

	def create
		@listing = Listing.new(listing_params)

		if @listing.save
			redirect_to @listing, notice: "Successfully created new listing"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @listing.update(listing_params)
			redirect_to @listing
		else
			render 'edit'
		end
	end

	def destroy
		@listing.destroy
		redirect_to root_path, notice: "Successfully deleted listing"
	end

	private

	def listing_params
		params.require(:listing).permit(:title, :year, :make, :jet_model, :serial_number, :location, :description, :tags, :image, :price, details_attributes: [:id, :name, :_destroy],specs_attributes: [:id, :status, :_destroy])
	end

	def find_listing
		@listing = Listing.find(params[:id])
	end
end

# ingredients_attributes: [:id, :name, :_destroy], aircraft_specs_attributes: [:id, :step, :_destroy])

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/home/index.html.erb
<h1>Welcome to Jets on Deck</h1>
<p><%= link_to 'Sign Up', new_user_registration_path %></p>
<p><%= link_to 'Log In', new_user_session_path %></p>

app/views/home/index.html.haml
%h1 Welcome to Jets on Deck

= link_to 'Sign Up', new_user_registration_path
= link_to 'Sign In', new_user_session_path

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title jets on Deck App
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags

%body
	%nav.navbar.navbar-default
		.container
			.navbar-brand= link_to "Jets on Deck", root_path

			- if user_signed_in?
				%ul.nav.navbar-nav.navbar-right
					%li= link_to "Post a new Listing", new_listing_path
					%li= link_to "Sign Out", destroy_user_session_path, method: :delete
			- else
				%ul.nav.navbar-nav.navbar-right
					%li= link_to "Sign Up", new_user_registration_path
					%li= link_to "Sign In", new_user_session_path

	.container
		- flash.each do |name, msg|
			= content_tag :div, msg, class: "alert"

		= yield

app/views/listings/_detail_fields.html.haml
.form-inline.clearfix
	.nested-fields
		= f.input :name, input_html: { class: 'form-input form-control' }
		= link_to_remove_association "Remove Step", f, class: "btn btn-default form-button"

app/views/listings/_form.html.haml
= simple_form_for @listing, html: { multipart: true } do |f|
	- if @listing.errors.any?
		#errors
			%p
				= @listing.errors.count
				Prevented this listing froms saving
			%ul
				- @listing.errors.full_messages.each do |msg|
					%li= msg
	.panel-body
		= f.input :title, input_html: { class: 'form-control' }
		= f.input :year, input_html: { class: 'form-control' }
		= f.input :make, input_html: { class: 'form-control' }
		= f.input :jet_model, input_html: { class: 'form-control' }
		= f.input :serial_number, input_html: { class: 'form-control' }
		= f.input :location, input_html: { class: 'form-control' }
		= f.input :tags, input_html: { class: 'form-control' }
		= f.input :description, input_html: { class: 'form-control' }
		= f.input :price, input_html: { class: 'form-control' }
		= f.input :image, input_html: { class: 'form-control' }

		.row
			.col-md-6
				%h3 Contact Details
				#details
					= f.simple_fields_for :details do |detail|
						= render 'detail_fields', f: detail
					.links
						= link_to_add_association 'Add detail', f, :details, class: "btn btn-default add-button"

			.col-md-6
				%h3 specs
				#specs
					= f.simple_fields_for :specs do |spec|
						= render 'spec_fields', f: spec
					.links
						= link_to_add_association 'Add Step', f, :specs, class: "btn btn-default add-button"

	= f.button :submit, class: "btn btn-primary"

app/views/listings/_spec_fields.html.haml
.form-inline.clearfix
	.nested-fields
		= f.input :status, input_html: { class: 'form-input form-control' }
		= link_to_remove_association "Remove status", f, class: "btn btn-default form-button"

app/views/listings/edit.html.haml
%h1 Edit Listing


= render 'form'

%br/

= link_to "Back", listing_path, class: "btn btn-default"

app/views/listings/index.html.haml
- @listing.each_slice(3) do |listings|
	.row
		- listings.each do |listing|
			.col-md-4
				.listing
					.image_wrapper
						= link_to listing do
							= image_tag listing.image.url(:medium)
					%h2= link_to listing.title, listing

app/views/listings/new.html.haml
%h1 New Listing


= render 'form'

%br/

= link_to "Back", root_path, class: "btn btn-default"

app/views/listings/show.html.haml
.main_content
	#listing_top.row
		.col-md-4
			= image_tag @listing.image.url(:medium), class: "listing_image"
		.col-md-8
			#listing_info
				%h1= simple_format (@listing.title)
				%p= @listing.description
			

	.row
		.col-md-6
			#details
				%h2 Contact Details
				%ul
					- @listing.details.each do |detail|
						%li= detail.name

		.col-md-6
			#specs
				%h2 Specs
				%ul
					- @listing.specs.each do |spec|
						%li= spec.status


	.row
		.col-md-12
			= link_to "Back", root_path, class: "btn btn-default"
			- if user_signed_in?
				= link_to "Edit", edit_listing_path, class: "btn btn-default"
				= link_to "Delete", listing_path, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-default"